//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.Database
{

    public partial class Contracts : XPLiteObject
    {
        int fOid;
        [Key]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
        string fTesto;
        [Size(SizeAttribute.Unlimited)]
        public string Testo
        {
            get { return fTesto; }
            set { SetPropertyValue<string>(nameof(Testo), ref fTesto, value); }
        }
        DateTime fDataInizio;
        public DateTime DataInizio
        {
            get { return fDataInizio; }
            set { SetPropertyValue<DateTime>(nameof(DataInizio), ref fDataInizio, value); }
        }
        DateTime fDataFine;
        public DateTime DataFine
        {
            get { return fDataFine; }
            set { SetPropertyValue<DateTime>(nameof(DataFine), ref fDataFine, value); }
        }
        Condominium fCondominium;
        [Association(@"ContractsReferencesCondominium")]
        public Condominium Condominium
        {
            get { return fCondominium; }
            set { SetPropertyValue<Condominium>(nameof(Condominium), ref fCondominium, value); }
        }
    }

}
