//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.simba_condomini
{

    [Persistent(@"__RefactorLog")]
    public partial class P__RefactorLog : XPLiteObject
    {
        Guid fOperationKey;
        [Key(true)]
        public Guid OperationKey
        {
            get { return fOperationKey; }
            set { SetPropertyValue<Guid>(nameof(OperationKey), ref fOperationKey, value); }
        }
    }

}
