//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.Database
{

    public partial class Provincia : XPObject
    {
        string fDESCRIZIONE;
        [Size(1000)]
        public string DESCRIZIONE
        {
            get { return fDESCRIZIONE; }
            set { SetPropertyValue<string>(nameof(DESCRIZIONE), ref fDESCRIZIONE, value); }
        }
        string fSIGLA;
        [Size(2)]
        public string SIGLA
        {
            get { return fSIGLA; }
            set { SetPropertyValue<string>(nameof(SIGLA), ref fSIGLA, value); }
        }
        string fCODICEPROVINCIA;
        [Size(3)]
        public string CODICEPROVINCIA
        {
            get { return fCODICEPROVINCIA; }
            set { SetPropertyValue<string>(nameof(CODICEPROVINCIA), ref fCODICEPROVINCIA, value); }
        }
        Regione fREGIONE;
        [Association(@"ProvinciaReferencesRegione")]
        public Regione REGIONE
        {
            get { return fREGIONE; }
            set { SetPropertyValue<Regione>(nameof(REGIONE), ref fREGIONE, value); }
        }
        [Association(@"ComuniReferencesProvincia")]
        public XPCollection<Comuni> Comunis { get { return GetCollection<Comuni>(nameof(Comunis)); } }
    }

}
