//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.Database
{

    public partial class Provincia : XPLiteObject
    {
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
        string fDescrizione;
        [Size(1000)]
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        string fSigla;
        [Size(2)]
        public string Sigla
        {
            get { return fSigla; }
            set { SetPropertyValue<string>(nameof(Sigla), ref fSigla, value); }
        }
        string fCodiceProvincia;
        [Size(3)]
        public string CodiceProvincia
        {
            get { return fCodiceProvincia; }
            set { SetPropertyValue<string>(nameof(CodiceProvincia), ref fCodiceProvincia, value); }
        }
        Regione fRegione;
        [Association(@"ProvinciaReferencesRegione")]
        public Regione Regione
        {
            get { return fRegione; }
            set { SetPropertyValue<Regione>(nameof(Regione), ref fRegione, value); }
        }
        [Association(@"ComuniReferencesProvincia")]
        public XPCollection<Comuni> Comunis { get { return GetCollection<Comuni>(nameof(Comunis)); } }
    }

}
