//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.simba_condomini
{

    public partial class Regione : XPObject
    {
        string fCODICEREGIONE;
        [Size(2)]
        public string CODICEREGIONE
        {
            get { return fCODICEREGIONE; }
            set { SetPropertyValue<string>(nameof(CODICEREGIONE), ref fCODICEREGIONE, value); }
        }
        string fDESCRIZIONE;
        [Size(1000)]
        public string DESCRIZIONE
        {
            get { return fDESCRIZIONE; }
            set { SetPropertyValue<string>(nameof(DESCRIZIONE), ref fDESCRIZIONE, value); }
        }
        string fNAZIONE;
        [Size(500)]
        public string NAZIONE
        {
            get { return fNAZIONE; }
            set { SetPropertyValue<string>(nameof(NAZIONE), ref fNAZIONE, value); }
        }
        [Association(@"ProvinciaReferencesRegione")]
        public XPCollection<Provincia> Provincias { get { return GetCollection<Provincia>(nameof(Provincias)); } }
    }

}
