//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.Database
{

    public partial class Regione : XPLiteObject
    {
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
        string fCodiceRegione;
        [Size(2)]
        public string CodiceRegione
        {
            get { return fCodiceRegione; }
            set { SetPropertyValue<string>(nameof(CodiceRegione), ref fCodiceRegione, value); }
        }
        string fDescrizione;
        [Size(1000)]
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
        string fNazione;
        [Size(500)]
        public string Nazione
        {
            get { return fNazione; }
            set { SetPropertyValue<string>(nameof(Nazione), ref fNazione, value); }
        }
        [Association(@"ProvinciaReferencesRegione")]
        public XPCollection<Provincia> Provincias { get { return GetCollection<Provincia>(nameof(Provincias)); } }
    }

}
