//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.Database
{

    public partial class TicketStatuses : XPLiteObject
    {
        Ticket fIdTicket;
        [Association(@"TicketStatusesReferencesTicket")]
        public Ticket IdTicket
        {
            get { return fIdTicket; }
            set { SetPropertyValue<Ticket>(nameof(IdTicket), ref fIdTicket, value); }
        }
        TicketStatus fIdStatus;
        [Association(@"TicketStatusesReferencesTicketStatus")]
        public TicketStatus IdStatus
        {
            get { return fIdStatus; }
            set { SetPropertyValue<TicketStatus>(nameof(IdStatus), ref fIdStatus, value); }
        }
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        User fIdUser;
        [Association(@"TicketStatusesReferencesUser")]
        public User IdUser
        {
            get { return fIdUser; }
            set { SetPropertyValue<User>(nameof(IdUser), ref fIdUser, value); }
        }
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
        string fDescrizione;
        public string Descrizione
        {
            get { return fDescrizione; }
            set { SetPropertyValue<string>(nameof(Descrizione), ref fDescrizione, value); }
        }
    }

}
