//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.simba_condomini
{

    public partial class TicketClassifications : XPLiteObject
    {
        Ticket fIdTicket;
        [Association(@"TicketClassificationsReferencesTicket")]
        public Ticket IdTicket
        {
            get { return fIdTicket; }
            set { SetPropertyValue<Ticket>(nameof(IdTicket), ref fIdTicket, value); }
        }
        TicketClassification fIdClassification;
        [Association(@"TicketClassificationsReferencesTicketClassification")]
        public TicketClassification IdClassification
        {
            get { return fIdClassification; }
            set { SetPropertyValue<TicketClassification>(nameof(IdClassification), ref fIdClassification, value); }
        }
        DateTime fDateInser;
        public DateTime DateInser
        {
            get { return fDateInser; }
            set { SetPropertyValue<DateTime>(nameof(DateInser), ref fDateInser, value); }
        }
        User fUserId;
        [Association(@"TicketClassificationsReferencesUser")]
        public User UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<User>(nameof(UserId), ref fUserId, value); }
        }
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
    }

}
