//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.simba_condomini
{

    public partial class TicketDocument : XPLiteObject
    {
        Ticket fIdTicket;
        [Association(@"TicketDocumentReferencesTicket")]
        public Ticket IdTicket
        {
            get { return fIdTicket; }
            set { SetPropertyValue<Ticket>(nameof(IdTicket), ref fIdTicket, value); }
        }
        Documents fIdDocument;
        [Association(@"TicketDocumentReferencesDocuments")]
        public Documents IdDocument
        {
            get { return fIdDocument; }
            set { SetPropertyValue<Documents>(nameof(IdDocument), ref fIdDocument, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        User fUserId;
        [Association(@"TicketDocumentReferencesUser")]
        public User UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<User>(nameof(UserId), ref fUserId, value); }
        }
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
    }

}
