//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.simba_condomini
{

    public partial class TicketSuplliers : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Ticket fIdTicket;
        [Association(@"TicketSuplliersReferencesTicket")]
        public Ticket IdTicket
        {
            get { return fIdTicket; }
            set { SetPropertyValue<Ticket>(nameof(IdTicket), ref fIdTicket, value); }
        }
        User fIdSuplier;
        [Association(@"TicketSuplliersReferencesUser")]
        public User IdSuplier
        {
            get { return fIdSuplier; }
            set { SetPropertyValue<User>(nameof(IdSuplier), ref fIdSuplier, value); }
        }
        DateTime fDateAdded;
        public DateTime DateAdded
        {
            get { return fDateAdded; }
            set { SetPropertyValue<DateTime>(nameof(DateAdded), ref fDateAdded, value); }
        }
        User fUser;
        [Association(@"TicketSuplliersReferencesUser1")]
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
    }

}
