//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.simba_condomini
{

    public partial class TicketStatuses : XPLiteObject
    {
        DateTime fData;
        public DateTime Data
        {
            get { return fData; }
            set { SetPropertyValue<DateTime>(nameof(Data), ref fData, value); }
        }
        int fIdUser;
        public int IdUser
        {
            get { return fIdUser; }
            set { SetPropertyValue<int>(nameof(IdUser), ref fIdUser, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("IdTicket")]
            public int IdTicket { get; set; }
            [Persistent("IdStatus")]
            public int IdStatus { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
