//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Simba.DataLayer.Database
{

    public partial class UserCondominium : XPLiteObject
    {
        User fIdUser;
        [Association(@"UserCondominiumReferencesUser")]
        public User IdUser
        {
            get { return fIdUser; }
            set { SetPropertyValue<User>(nameof(IdUser), ref fIdUser, value); }
        }
        Condominium fIdCondominium;
        [Association(@"UserCondominiumReferencesCondominium")]
        public Condominium IdCondominium
        {
            get { return fIdCondominium; }
            set { SetPropertyValue<Condominium>(nameof(IdCondominium), ref fIdCondominium, value); }
        }
        int fOid;
        [Key(true)]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
    }

}
