CREATE TABLE [dbo].[Comuni]
(
	[Oid] INT NOT NULL PRIMARY KEY,
	[RIPARTIZIONEGEOGRAFICA] [varchar](1000) NULL,
	[CODICENUTS22010] [varchar](1000) NULL,
	[CODICENUTS32010] [varchar](1000) NULL,
	[CODICEREGIONE] [varchar](1000) NULL,
	[CODICEPROVINCIA] [varchar](1000) NULL,
	[CODICECITTAMETROPOLITANA] [varchar](1000) NULL,
	[NUMPROGRESSIVOCOMUNE] [varchar](1000) NULL,
	[CODICEISTAT] [varchar](1000) NULL,
	[CODICEISTATNUM] [varchar](1000) NULL,
	[CODICEISTAT107PROV] [varchar](1000) NULL,
	[CODICEISTAT103PROV] [varchar](1000) NULL,
	[CODICECATASTALE] [varchar](1000) NULL,
	[DENOMINAZIONEITALIANO] [varchar](1000) NULL,
	[CAPOLUOGODIPROVINCIA] [varchar](1000) NULL,
	[ZONAALTIMETRICA] [varchar](1000) NULL,
	[ALTITUDINEDELCENTRO] [varchar](1000) NULL,
	[COMUNELITORANEO] [varchar](1000) NULL,
	[COMUNEMONTANO] [varchar](1000) NULL,
	[SUPERFICIETERRITORIALE] [varchar](1000) NULL,
	[POPOLAZIONE2001] [varchar](1000) NULL,
	[POPOLAZIONE2011] [varchar](1000) NULL,
	[PROVINCIA] [int] NULL, 
    CONSTRAINT [FK_Comuni_Provincia] FOREIGN KEY ([PROVINCIA]) REFERENCES [PROVINCIA]([Oid])
	
)


