using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RS
{
    public sealed class Nations : Dictionary<string, Nation>
    {
        public static readonly Nation UNKNOWN_NATION = new Nation("??", "??");
        public static readonly Nation NO_NATION = new Nation("**", "**");

        public Nation getPhoneNumberNation(string phone_number)
        {
            if (string.IsNullOrEmpty(phone_number))
                return UNKNOWN_NATION;
            foreach (KeyValuePair<string, Nation> kvp in this)
            {
                if (phone_number.StartsWith(kvp.Value.Prefix))
                    return kvp.Value;
            }
            return UNKNOWN_NATION;
        }

        public static readonly Nation ARUBA = new Nation("AW", "+297");
        public static readonly Nation AFGHANISTAN = new Nation("AF", "+93");
        public static readonly Nation ANGOLA = new Nation("AO", "+244");
        public static readonly Nation ALBANIA = new Nation("AL", "+355");
        public static readonly Nation ANDORRA = new Nation("AD", "+376");
        public static readonly Nation NETHERLANDS_ANTILLES = new Nation("AN", "+599");
        public static readonly Nation UNITED_ARAB_EMIRATES = new Nation("AE", "+971");
        public static readonly Nation ARGENTINA = new Nation("AR", "+54");
        public static readonly Nation ARMENIA = new Nation("AM", "+374");
        public static readonly Nation AMERICAN_SAMOA = new Nation("AS", "+684");
        public static readonly Nation AUSTRALIA = new Nation("AU", "+61");
        public static readonly Nation AUSTRIA = new Nation("AT", "+43");
        public static readonly Nation AZERBAIJAN = new Nation("AZ", "+994");
        public static readonly Nation BURUNDI = new Nation("BI", "+257");
        public static readonly Nation BELGIUM = new Nation("BE", "+32");
        public static readonly Nation BENIN = new Nation("BJ", "+229");
        public static readonly Nation BURKINA_FASO = new Nation("BF", "+226");
        public static readonly Nation BANGLADESH = new Nation("BD", "+880");
        public static readonly Nation BAHRAIN = new Nation("BH", "+973");
        public static readonly Nation BOSNIA_AND_HERZEGOVINA = new Nation("BA", "+387");
        public static readonly Nation BELARUS = new Nation("BY", "+375");
        public static readonly Nation BELIZE = new Nation("BZ", "+501");
        public static readonly Nation BOLIVIA = new Nation("BO", "+591");
        public static readonly Nation BRAZIL = new Nation("BR", "+55");
        public static readonly Nation BRUNEI_DARUSSALAM = new Nation("BN", "+673");
        public static readonly Nation BHUTAN = new Nation("BT", "+975");
        public static readonly Nation BOTSWANA = new Nation("BW", "+267");
        public static readonly Nation CENTRAL_AFRICAN_REPUBLIC = new Nation("CF", "+236");
        public static readonly Nation CHILE = new Nation("CL", "+56");
        public static readonly Nation CHINA = new Nation("CN", "+86");
        public static readonly Nation CAMEROON = new Nation("CM", "+237");
        public static readonly Nation THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO = new Nation("CD", "+243");
        public static readonly Nation CONGO = new Nation("CG", "+242");
        public static readonly Nation COOK_ISLANDS = new Nation("CK", "+682");
        public static readonly Nation COLOMBIA = new Nation("CO", "+57");
        public static readonly Nation COMOROS = new Nation("KM", "+269");
        public static readonly Nation CAPE_VERDE = new Nation("CV", "+238");
        public static readonly Nation COSTA_RICA = new Nation("CR", "+506");
        public static readonly Nation CUBA = new Nation("CU", "+53");
        public static readonly Nation CYPRUS = new Nation("CY", "+357");
        public static readonly Nation CZECH_REPUBLIC = new Nation("CZ", "+420");
        public static readonly Nation DENMARK = new Nation("DK", "+45");
        public static readonly Nation GERMANY = new Nation("DE", "+49");
        public static readonly Nation DJIBOUTI = new Nation("DJ", "+253");
        public static readonly Nation ALGERIA = new Nation("DZ", "+213");
        public static readonly Nation ECUADOR = new Nation("EC", "+593");
        public static readonly Nation ERITREA = new Nation("ER", "+291");
        public static readonly Nation SPAIN = new Nation("ES", "+34");
        public static readonly Nation ESTONIA = new Nation("EE", "+372");
        public static readonly Nation ETHIOPIA = new Nation("ET", "+251");
        public static readonly Nation FINLAND = new Nation("FI", "+358");
        public static readonly Nation FIJI = new Nation("FJ", "+679");
        public static readonly Nation FALKLAND_ISLANDS = new Nation("FK", "+500");
        public static readonly Nation FRANCE = new Nation("FR", "+33");
        public static readonly Nation FAROE_ISLANDS = new Nation("FO", "+298");
        public static readonly Nation MICRONESIA = new Nation("FM", "+691");
        public static readonly Nation GABON = new Nation("GA", "+241");
        public static readonly Nation UNITED_KINGDOM = new Nation("GB", "+44");
        public static readonly Nation GEORGIA = new Nation("GE", "+995");
        public static readonly Nation GHANA = new Nation("GH", "+233");
        public static readonly Nation GIBRALTAR = new Nation("GI", "+350");
        public static readonly Nation GUINEA = new Nation("GN", "+224");
        public static readonly Nation GAMBIA = new Nation("GM", "+220");
        public static readonly Nation GUINEA_BISSAU = new Nation("GW", "+245");
        public static readonly Nation EQUATORIAL_GUINEA = new Nation("GQ", "+240");
        public static readonly Nation GREECE = new Nation("GR", "+30");
        public static readonly Nation GREENLAND = new Nation("GL", "+299");
        public static readonly Nation GUATEMALA = new Nation("GT", "+502");
        public static readonly Nation FRENCH_GUIANA = new Nation("GF", "+594");
        public static readonly Nation GUYANA = new Nation("GY", "+592");
        public static readonly Nation HONG_KONG = new Nation("HK", "+852");
        public static readonly Nation HONDURAS = new Nation("HN", "+504");
        public static readonly Nation CROATIA = new Nation("HR", "+385");
        public static readonly Nation HAITI = new Nation("HT", "+509");
        public static readonly Nation HUNGARY = new Nation("HU", "+36");
        public static readonly Nation INDIA = new Nation("IN", "+91");
        public static readonly Nation IRELAND = new Nation("IE", "+353");
        public static readonly Nation ISLAMIC_REPUBLIC_OF_IRAN = new Nation("IR", "+98");
        public static readonly Nation IRAQ = new Nation("IQ", "+964");
        public static readonly Nation ICELAND = new Nation("IS", "+354");
        public static readonly Nation ISRAEL = new Nation("IL", "+972");
        public static readonly Nation ITALY = new Nation("IT", "+39");
        public static readonly Nation JORDAN = new Nation("JO", "+962");
        public static readonly Nation JAPAN = new Nation("JP", "+81");
        public static readonly Nation KENYA = new Nation("KE", "+254");
        public static readonly Nation KYRGYZSTAN = new Nation("KG", "+996");
        public static readonly Nation CAMBODIA = new Nation("KH", "+855");
        public static readonly Nation KIRIBATI = new Nation("KI", "+686");
        public static readonly Nation REPUBLIC_OF_KOREA = new Nation("KR", "+82");
        public static readonly Nation KUWAIT = new Nation("KW", "+965");
        public static readonly Nation LEBANON = new Nation("LB", "+961");
        public static readonly Nation LIBERIA = new Nation("LR", "+231");
        public static readonly Nation LIECHTENSTEIN = new Nation("LI", "+423");
        public static readonly Nation SRI_LANKA = new Nation("LK", "+94");
        public static readonly Nation LESOTHO = new Nation("LS", "+266");
        public static readonly Nation LITHUANIA = new Nation("LT", "+370");
        public static readonly Nation LUXEMBOURG = new Nation("LU", "+352");
        public static readonly Nation LATVIA = new Nation("LV", "+371");
        public static readonly Nation MACAO = new Nation("MO", "+853");
        public static readonly Nation MOROCCO = new Nation("MA", "+212");
        public static readonly Nation MONACO = new Nation("MC", "+377");
        public static readonly Nation MOLDOVA = new Nation("MD", "+373");
        public static readonly Nation MADAGASCAR = new Nation("MG", "+261");
        public static readonly Nation MALDIVES = new Nation("MV", "+960");
        public static readonly Nation MEXICO = new Nation("MX", "+52");
        public static readonly Nation MARSHALL_ISLANDS = new Nation("MH", "+692");
        public static readonly Nation THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA = new Nation("MK", "+389");
        public static readonly Nation MALI = new Nation("ML", "+223");
        public static readonly Nation MALTA = new Nation("MT", "+356");
        public static readonly Nation MYANMAR = new Nation("MM", "+95");
        public static readonly Nation MONGOLIA = new Nation("MN", "+976");
        public static readonly Nation MOZAMBIQUE = new Nation("MZ", "+258");
        public static readonly Nation MAURITANIA = new Nation("MR", "+222");
        public static readonly Nation MARTINIQUE = new Nation("MQ", "+596");
        public static readonly Nation MAURITIUS = new Nation("MU", "+230");
        public static readonly Nation MALAWI = new Nation("MW", "+265");
        public static readonly Nation MAYOTTE = new Nation("YT", "+269");
        public static readonly Nation NAMIBIA = new Nation("NA", "+264");
        public static readonly Nation NEW_CALEDONIA = new Nation("NC", "+687");
        public static readonly Nation NETHERLANDS = new Nation("NL", "+31");
        public static readonly Nation NIGER = new Nation("NE", "+227");
        public static readonly Nation NIGERIA = new Nation("NG", "+234");
        public static readonly Nation NICARAGUA = new Nation("NI", "+505");
        public static readonly Nation NIUE = new Nation("NU", "+683");
        public static readonly Nation NORWAY = new Nation("NO", "+47");
        public static readonly Nation NEPAL = new Nation("NP", "+977");
        public static readonly Nation NAURU = new Nation("NR", "+674");
        public static readonly Nation NEW_ZEALAND = new Nation("NZ", "+64");
        public static readonly Nation OMAN = new Nation("OM", "+968");
        public static readonly Nation PAKISTAN = new Nation("PK", "+92");
        public static readonly Nation PANAMA = new Nation("PA", "+507");
        public static readonly Nation PERU = new Nation("PE", "+51");
        public static readonly Nation PHILIPPINES = new Nation("PH", "+63");
        public static readonly Nation PALAU = new Nation("PW", "+680");
        public static readonly Nation PAPUA_NEW_GUINEA = new Nation("PG", "+675");
        public static readonly Nation POLAND = new Nation("PL", "+48");
        public static readonly Nation PORTUGAL = new Nation("PT", "+351");
        public static readonly Nation DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA = new Nation("KP", "+850");
        public static readonly Nation PARAGUAY = new Nation("PY", "+595");
        public static readonly Nation FRENCH_POLYNESIA = new Nation("PF", "+689");
        public static readonly Nation QATAR = new Nation("QA", "+974");
        public static readonly Nation REUNION = new Nation("RE", "+262");
        public static readonly Nation ROMANIA = new Nation("RO", "+40");
        public static readonly Nation RUSSIAN_FEDERATION = new Nation("RU", "+7");
        public static readonly Nation RWANDA = new Nation("RW", "+250");
        public static readonly Nation SAUDI_ARABIA = new Nation("SA", "+966");
        public static readonly Nation SUDAN = new Nation("SD", "+249");
        public static readonly Nation SENEGAL = new Nation("SN", "+221");
        public static readonly Nation SINGAPORE = new Nation("SG", "+65");
        public static readonly Nation SAINT_HELENA = new Nation("SH", "+290");
        public static readonly Nation SOLOMON_ISLANDS = new Nation("SB", "+677");
        public static readonly Nation SIERRA_LEONE = new Nation("SL", "+232");
        public static readonly Nation SLOVENIA = new Nation("SI", "+386");
        public static readonly Nation EL_SALVADOR = new Nation("SV", "+503");
        public static readonly Nation SAN_MARINO = new Nation("SM", "+378");
        public static readonly Nation SOMALIA = new Nation("SO", "+252");
        public static readonly Nation SAINT_PIERRE_AND_MIQUELON = new Nation("PM", "+508");
        public static readonly Nation SAO_TOME_AND_PRINCIPE = new Nation("ST", "+239");
        public static readonly Nation SWITZERLAND = new Nation("CH", "+41");
        public static readonly Nation SURINAME = new Nation("SR", "+597");
        public static readonly Nation SLOVAKIA = new Nation("SK", "+421");
        public static readonly Nation SWEDEN = new Nation("SE", "+46");
        public static readonly Nation SWAZILAND = new Nation("SZ", "+268");
        public static readonly Nation SEYCHELLES = new Nation("SC", "+248");
        public static readonly Nation SYRIAN_ARAB_REPUBLIC = new Nation("SY", "+963");
        public static readonly Nation CHAD = new Nation("TD", "+235");
        public static readonly Nation TOGO = new Nation("TG", "+228");
        public static readonly Nation THAILAND = new Nation("TH", "+66");
        public static readonly Nation TAJIKISTAN = new Nation("TJ", "+992");
        public static readonly Nation TOKELAU = new Nation("TK", "+690");
        public static readonly Nation TURKMENISTAN = new Nation("TM", "+993");
        public static readonly Nation TONGA = new Nation("TO", "+676");
        public static readonly Nation TUNISIA = new Nation("TN", "+216");
        public static readonly Nation TURKEY = new Nation("TR", "+90");
        public static readonly Nation TUVALU = new Nation("TV", "+688");
        public static readonly Nation TAIWAN = new Nation("TW", "+886");
        public static readonly Nation TANZANIA = new Nation("TZ", "+255");
        public static readonly Nation UGANDA = new Nation("UG", "+256");
        public static readonly Nation UKRAINE = new Nation("UA", "+380");
        public static readonly Nation URUGUAY = new Nation("UY", "+598");
        public static readonly Nation UNITED_STATES = new Nation("US", "+1");
        public static readonly Nation UZBEKISTAN = new Nation("UZ", "+998");
        public static readonly Nation VENEZUELA = new Nation("VE", "+58");
        public static readonly Nation VIET_NAM = new Nation("VN", "+84");
        public static readonly Nation VANUATU = new Nation("VU", "+678");
        public static readonly Nation WALLIS_AND_FUTUNA = new Nation("WF", "+681");
        public static readonly Nation SAMOA = new Nation("WS", "+685");
        public static readonly Nation YEMEN = new Nation("YE", "+967");
        public static readonly Nation SOUTH_AFRICA = new Nation("ZA", "+27");
        public static readonly Nation ZAMBIA = new Nation("ZM", "+260");
        public static readonly Nation ZIMBABWE = new Nation("ZW", "+263");

        private Nations() {
            Add("AW", ARUBA);
            Add("AF", AFGHANISTAN);
            Add("AO", ANGOLA);
            Add("AL", ALBANIA);
            Add("AD", ANDORRA);
            Add("AN", NETHERLANDS_ANTILLES);
            Add("AE", UNITED_ARAB_EMIRATES);
            Add("AR", ARGENTINA);
            Add("AM", ARMENIA);
            Add("AS", AMERICAN_SAMOA);
            Add("AU", AUSTRALIA);
            Add("AT", AUSTRIA);
            Add("AZ", AZERBAIJAN);
            Add("BI", BURUNDI);
            Add("BE", BELGIUM);
            Add("BJ", BENIN);
            Add("BF", BURKINA_FASO);
            Add("BD", BANGLADESH);
            Add("BH", BAHRAIN);
            Add("BA", BOSNIA_AND_HERZEGOVINA);
            Add("BY", BELARUS);
            Add("BZ", BELIZE);
            Add("BO", BOLIVIA);
            Add("BR", BRAZIL);
            Add("BN", BRUNEI_DARUSSALAM);
            Add("BT", BHUTAN);
            Add("BW", BOTSWANA);
            Add("CF", CENTRAL_AFRICAN_REPUBLIC);
            Add("CL", CHILE);
            Add("CN", CHINA);
            Add("CM", CAMEROON);
            Add("CD", THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO);
            Add("CG", CONGO);
            Add("CK", COOK_ISLANDS);
            Add("CO", COLOMBIA);
            Add("KM", COMOROS);
            Add("CV", CAPE_VERDE);
            Add("CR", COSTA_RICA);
            Add("CU", CUBA);
            Add("CY", CYPRUS);
            Add("CZ", CZECH_REPUBLIC);
            Add("DK", DENMARK);
            Add("DE", GERMANY);
            Add("DJ", DJIBOUTI);
            Add("DZ", ALGERIA);
            Add("EC", ECUADOR);
            Add("ER", ERITREA);
            Add("ES", SPAIN);
            Add("EE", ESTONIA);
            Add("ET", ETHIOPIA);
            Add("FI", FINLAND);
            Add("FJ", FIJI);
            Add("FK", FALKLAND_ISLANDS);
            Add("FR", FRANCE);
            Add("FO", FAROE_ISLANDS);
            Add("FM", MICRONESIA);
            Add("GA", GABON);
            Add("GB", UNITED_KINGDOM);
            Add("GE", GEORGIA);
            Add("GH", GHANA);
            Add("GI", GIBRALTAR);
            Add("GN", GUINEA);
            Add("GM", GAMBIA);
            Add("GW", GUINEA_BISSAU);
            Add("GQ", EQUATORIAL_GUINEA);
            Add("GR", GREECE);
            Add("GL", GREENLAND);
            Add("GT", GUATEMALA);
            Add("GF", FRENCH_GUIANA);
            Add("GY", GUYANA);
            Add("HK", HONG_KONG);
            Add("HN", HONDURAS);
            Add("HR", CROATIA);
            Add("HT", HAITI);
            Add("HU", HUNGARY);
            Add("IN", INDIA);
            Add("IE", IRELAND);
            Add("IR", ISLAMIC_REPUBLIC_OF_IRAN);
            Add("IQ", IRAQ);
            Add("IS", ICELAND);
            Add("IL", ISRAEL);
            Add("IT", ITALY);
            Add("JO", JORDAN);
            Add("JP", JAPAN);
            Add("KE", KENYA);
            Add("KG", KYRGYZSTAN);
            Add("KH", CAMBODIA);
            Add("KI", KIRIBATI);
            Add("KR", REPUBLIC_OF_KOREA);
            Add("KW", KUWAIT);
            Add("LB", LEBANON);
            Add("LR", LIBERIA);
            Add("LI", LIECHTENSTEIN);
            Add("LK", SRI_LANKA);
            Add("LS", LESOTHO);
            Add("LT", LITHUANIA);
            Add("LU", LUXEMBOURG);
            Add("LV", LATVIA);
            Add("MO", MACAO);
            Add("MA", MOROCCO);
            Add("MC", MONACO);
            Add("MD", MOLDOVA);
            Add("MG", MADAGASCAR);
            Add("MV", MALDIVES);
            Add("MX", MEXICO);
            Add("MH", MARSHALL_ISLANDS);
            Add("MK", THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA);
            Add("ML", MALI);
            Add("MT", MALTA);
            Add("MM", MYANMAR);
            Add("MN", MONGOLIA);
            Add("MZ", MOZAMBIQUE);
            Add("MR", MAURITANIA);
            Add("MQ", MARTINIQUE);
            Add("MU", MAURITIUS);
            Add("MW", MALAWI);
            Add("YT", MAYOTTE);
            Add("NA", NAMIBIA);
            Add("NC", NEW_CALEDONIA);
            Add("NL", NETHERLANDS);
            Add("NE", NIGER);
            Add("NG", NIGERIA);
            Add("NI", NICARAGUA);
            Add("NU", NIUE);
            Add("NO", NORWAY);
            Add("NP", NEPAL);
            Add("NR", NAURU);
            Add("NZ", NEW_ZEALAND);
            Add("OM", OMAN);
            Add("PK", PAKISTAN);
            Add("PA", PANAMA);
            Add("PE", PERU);
            Add("PH", PHILIPPINES);
            Add("PW", PALAU);
            Add("PG", PAPUA_NEW_GUINEA);
            Add("PL", POLAND);
            Add("PT", PORTUGAL);
            Add("KP", DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA);
            Add("PY", PARAGUAY);
            Add("PF", FRENCH_POLYNESIA);
            Add("QA", QATAR);
            Add("RE", REUNION);
            Add("RO", ROMANIA);
            Add("RU", RUSSIAN_FEDERATION);
            Add("RW", RWANDA);
            Add("SA", SAUDI_ARABIA);
            Add("SD", SUDAN);
            Add("SN", SENEGAL);
            Add("SG", SINGAPORE);
            Add("SH", SAINT_HELENA);
            Add("SB", SOLOMON_ISLANDS);
            Add("SL", SIERRA_LEONE);
            Add("SI", SLOVENIA);
            Add("SV", EL_SALVADOR);
            Add("SM", SAN_MARINO);
            Add("SO", SOMALIA);
            Add("PM", SAINT_PIERRE_AND_MIQUELON);
            Add("ST", SAO_TOME_AND_PRINCIPE);
            Add("CH", SWITZERLAND);
            Add("SR", SURINAME);
            Add("SK", SLOVAKIA);
            Add("SE", SWEDEN);
            Add("SZ", SWAZILAND);
            Add("SC", SEYCHELLES);
            Add("SY", SYRIAN_ARAB_REPUBLIC);
            Add("TD", CHAD);
            Add("TG", TOGO);
            Add("TH", THAILAND);
            Add("TJ", TAJIKISTAN);
            Add("TK", TOKELAU);
            Add("TM", TURKMENISTAN);
            Add("TO", TONGA);
            Add("TN", TUNISIA);
            Add("TR", TURKEY);
            Add("TV", TUVALU);
            Add("TW", TAIWAN);
            Add("TZ", TANZANIA);
            Add("UG", UGANDA);
            Add("UA", UKRAINE);
            Add("UY", URUGUAY);
            Add("US", UNITED_STATES);
            Add("UZ", UZBEKISTAN);
            Add("VE", VENEZUELA);
            Add("VN", VIET_NAM);
            Add("VU", VANUATU);
            Add("WF", WALLIS_AND_FUTUNA);
            Add("WS", SAMOA);
            Add("YE", YEMEN);
            Add("ZA", SOUTH_AFRICA);
            Add("ZM", ZAMBIA);
            Add("ZW", ZIMBABWE);
            Add("??", UNKNOWN_NATION);
            Add("**", NO_NATION);
        }

        private static Nations _instance = new Nations();
        public static Nations I {
            get {
                return _instance;
            }
        }

    }
}
