CREATE OR REPLACE TRIGGER "RDL_UNIVOCO"
  BEFORE INSERT ON RDL
  FOR EACH ROW

  WHEN (NEW.rdlunivoco IS NULL or NEW.rdlunivoco = 0)
BEGIN
  SELECT seq_rdlunivoco.NEXTVAL INTO :NEW.rdlunivoco FROM DUAL;
END;
/*RDLUNIVOCO  26073 
RRDLMP    
RRDLTTMP  292 NUMERO TICKET e MP*/
/
